name = "FMMLIB2D"
version = "0.3.1"
author = "Ludvig af Klinteberg <ludvigak@kth.se>"
uuid = "1a804d9e-d798-534b-a6a9-4525c36f0718"

[deps]
BinDeps = "9e28174c-4ba2-5203-b857-d8d62c4213ee"
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[compat]
julia = "â‰¥ 1.0.0"

[extras]
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[targets]
test = ["SpecialFunctions"]
